# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

version <- function() {
    invisible(.Call(`_omicsds_version`))
}

connect <- function(workspace, array) {
    .Call(`_omicsds_connect`, workspace, array)
}

disconnect <- function(handle) {
    invisible(.Call(`_omicsds_disconnect`, handle))
}

query <- function(handle) {
    invisible(.Call(`_omicsds_query`, handle))
}

rcpp_hello_world <- function() {
    .Call(`_omicsds_rcpp_hello_world`)
}

rcpp_vector_access1 <- function() {
    invisible(.Call(`_omicsds_rcpp_vector_access1`))
}

